keys:
  - &admin_julius EBE7 5BC0 5820 6BC9 F440  895F F7D6 E464 4ACD 05A4
  - &server_kreutz_fun age15hlm3wkxz7w524qgm8pqmcfgg5pn4qfdnkfm9q29zxq00rst0veq6xun3u
creation_rules:
  - path_regex: sops/secrets.yaml
    key_groups:
    - pgp:
      - *admin_julius
      age:
      - *server_kreutz_fun
